services:
  remitlytics-db:
    image: postgres:16-alpine
    container_name: remitlytics_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: remit_admin
      POSTGRES_PASSWORD: admin_secure_password123
      POSTGRES_DB: remitlytics_ledger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: